# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OC1gZlq6ZMd-CmZ_WSgm9IfKsdBbyvhF
"""

import joblib
import numpy as np
import pandas as pd

scaler_academic_performance_ratio = joblib.load("model/scaler_academic_performance_ratio.joblib")
scaler_averageGrade = joblib.load("model/scaler_average_grade.joblib")
scaler_eduParenting = joblib.load("model/scaler_edu_parenting.joblib")
scaler_pilihanPertama = joblib.load("model/scaler_first_choice.joblib")
scaler_tekananFinansial = joblib.load("model/scaler_tekanan_finansal.joblib")
scaler_totalEvaluation = joblib.load("model/scaler_total_evaluations.joblib")


def data_preprocessing(data):
    """Preprocessing data

    Args:
        data (Pandas DataFrame): Dataframe that contain all the data to make prediction

    return:
        Pandas DataFrame: Dataframe that contain all the preprocessed data
    """
    data = data.copy()
    df = pd.DataFrame()


    data["academic_performance_ratio"] = scaler_academic_performance_ratio.transform(np.asarray(data["academic_performance_ratio"]).reshape(-1,1))[0]
    data["average_grade"] = scaler_averageGrade.transform(np.asarray(data["average_grade"]).reshape(-1,1))[0]
    data["edu_parenting"] = scaler_eduParenting.transform(np.asarray(data["edu_parenting"]).reshape(-1,1))[0]
    data["first_choice"] = scaler_pilihanPertama.transform(np.asarray(data["first_choice"]).reshape(-1,1))[0]
    data["tekanan_finansal"] = scaler_tekananFinansial.transform(np.asarray(data["tekanan_finansal"]).reshape(-1,1))[0]
    data["total_evaluations"] = scaler_totalEvaluation.transform(np.asarray(data["total_evaluations"]).reshape(-1,1))[0]


    return df