# -*- coding: utf-8 -*-
"""dropOut_predict_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbhpxZ5NEDdvR0WzT4WM2TedsoSL7zpu
"""

import streamlit as st
import pandas as pd
import joblib
from data_preprocessing import data_preprocessing, encoder_Credit_Mix, encoder_Payment_Behaviour, encoder_Payment_of_Min_Amount
from prediction import prediction

col1, col2 = st.columns([1, 5])
with col1:
    st.image("images.png", width=130)
with col2:
    st.header('Dropout Predictor App (Prototype)')

    data = pd.DataFrame()

col1, col2, col3 = st.columns(3)

with col1:
    academic_performance_ratio = int(st.number_input(label='academic_performance_ratio', value=0.5))
    data["academic_performance_ratio"] = academic_performance_ratio

with st.expander("View the Raw Data"):
    st.dataframe(data=data, width=800, height=10)

if st.button('Predict'):
    new_data = data_preprocessing(data=data)
    with st.expander("View the Preprocessed Data"):
        st.dataframe(data=new_data, width=800, height=10)
    st.write("Dropout Rate Prediction: {}".format(prediction(new_data)))