# -*- coding: utf-8 -*-
"""dropOut_predict_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbhpxZ5NEDdvR0WzT4WM2TedsoSL7zpu
"""

import streamlit as st
import pandas as pd
import joblib
from data_preprocessing import data_preprocessing
from prediction import prediction

col1, col2 = st.columns([1, 5])
with col1:
    st.image("images.png", width=130)
with col2:
    st.header('Dropout Predictor App (Prototype)')

    data = pd.DataFrame()
 
# Create three columns to input data
col1, col2, col3 = st.columns(3)  # Unpack 3 columns
 
with col1:
    academic_performance_ratio = st.number_input(label='academic_performance_ratio')
    data["academic_performance_ratio"] = academic_performance_ratio

with st.expander("View the Raw Data"):
    st.dataframe(data=data, width=800, height=10)

if st.button('Predict'):

    st.write("Dropout Rate Prediction: {}".format(prediction(data)))
